### ISSUE TITLE
Cannot copy stream on iOS 

### ISSUE THREAD

**Issue by mybuntu-git2** [Stremio/stremio-web#352]
Hello, in iOS safari, logging in online via netlify, I get “stream is not supported, open in external player”.
 
 but then I am unable to copy the address to open it in an external player, safari says “ Safari cannot open the page because the address is invalid.”

request to put a copy link button next to the “open in” banner.

**Comment by elpiel** [comment]
Hello @mybuntu-git2 ,
thank you for reporting this issue.

Would you mind providing the url for the stream here?


You can copy the link from the 3 dots menu (the most right option) in the bottom right.
It should directly copy the link in your clipboard instead of opening it in the browser.

![Screenshot from 2023-04-20 16-10-57](https://user-images.githubusercontent.com/8925621/233376796-47d41421-01bd-4ce4-9b6a-d1253b6fc3cb.png)

**Comment by tymmesyde** [comment]
@elpiel  The options menu was hidden on mobile:
Opened a PR to fix it #359 
![image](https://user-images.githubusercontent.com/7889816/233555544-71f5c931-6ede-47d5-9211-277dd01ae2d7.png)
