### ISSUE TITLE
Confusing changes in Stremio Web shortcuts

### ISSUE THREAD

**Issue by s-a-m** [Stremio/stremio-web#413]
In Stremio, shortcuts for moving ahead/behind are (and have been for years afaik) the following [[1]](https://stremio.zendesk.com/hc/en-us/articles/360022892811-Shortcuts-in-stremio):
- Left arrow: 	Seek 20 seconds behind
- Right arrow: 	Seek 20 seconds ahead
- Shift + Left arrow: 	Seek 10 seconds behind
- Shift + Right arrow: 	Seek 10 seconds ahead

However, in Stremio Web, these shortcuts have changed values:
- Left arrow: 	Seek 10 seconds behind
- Right arrow: 	Seek 10 seconds ahead
- Shift + Left arrow: 	Seek 30 seconds behind
- Shift + Right arrow: 	Seek 30 seconds ahead

This is very confusing to be honest. I would suggest normalizing the values between both would be the optimal solution, whatever version. Personally, I'd prefer to stick to those that we are already used to.

**Comment by elpiel** [comment]
Hello, thanks for reporting this misalignment!

I will make sure to discuss it with the rest of the team if this was intended or we should change at least the shortcuts to match the combinations on Desktop (i.e. w/ shift - finer grain seeking)

**Comment by elpiel** [comment]
Hello, you can check out this PR in core and soon the changes should be also applied in stremio-web as not it uses a hardcoded ratio for seeking with the Shift key - https://github.com/Stremio/stremio-core/pull/546

Because most player use a seeking time of 10 seconds we are keeping this value as the default and instead providing a finer seeking time of **3 seconds**. You will be able to update your setting in stremio-web and make it consistent with stremio Desktop if you want.

Stremio Web seek shortcuts:

- Left arrow: Seek 10 seconds behind
- Right arrow: Seek 10 seconds ahead
- Shift + Left arrow: Seek 3 seconds behind
- Shift + Right arrow: Seek 3 seconds ahead
