### ISSUE TITLE
Video is not supported

### ISSUE THREAD

**Issue by alanmilinovic** [Stremio/stremio-web#604]
When I try to play stream in Chrome on my laptop it is saying "Video is not supported". The same stream is working in Chrome on my android phone. I guess it is codec related issue. Any advice?

**Comment by alanmilinovic** [comment]
Ok, so it is not working because I am using a hostname and not localhost or local IP.

**Comment by davidvn001** [comment]
> Ok, so it is not working because I am using a hostname and not localhost or local IP.

Hi,

How and where to configure using localhost or local IP?

**Comment by alanmilinovic** [comment]
> > Ok, so it is not working because I am using a hostname and not localhost or local IP.
> 
> Hi,
> 
> How and where to configure using localhost or local IP?

Not possible.

**Comment by gloatoriginal** [comment]
It seems to be very hit or miss with Stremio web, I have one hosted on a headless server (endeavourOS) within a podman container. Sometimes I'm able to stream torrentio -> stremio via stremio web and local caching on the server, this is very rare. However I'm able to stream the same torrentio through my RD setup within the same stremio web app. There's something amiss with local caching vs RD option and I'm not qualified enough to understand what the hold up is.

My preference to cache locally comes from the stremio container piped through a VPN connection in which I can have only connection to that VPN provider, when I introduce Debrid solutions it has another access point of where my data needs to be associated.

Whats another oddity is that from my android device into the stremio web I can stream mediafusion live events but I'm unable to for the same stream on my PC using the same browser, Microsoft Edge. This leads me to believe that it maybe something on my desktop client side.

For added technical reference, stremio is hosted on 2 services via my LAN, stremio.local (ip:8083) and stremio-service.local (ip:11470), these both are opened via the main container and the VPN container in network mode.

Thought I'd add my 2 cents because I've had mixed results streaming with torrentio -> stremio web, which isn't present in the same stremio web with torrentio -> real debrid -> stremio web.

**EDIT** fixed wording on domain name.

**Comment by alanmilinovic** [comment]
> It seems to be very hit or miss with Stremio web, I have one hosted on a headless server (endeavourOS) within a podman container. Sometimes I'm able to stream torrentio -> stremio via stremio web and local caching on the server, this is very rare. However I'm able to stream the same torrentio through my RD setup within the same stremio web app. There's something amiss with local caching vs RD option and I'm not qualified enough to understand what the hold up is.
> 
> My preference to cache locally comes from the stremio container piped through a VPN connection in which I can have only connection to that VPN provider, when I introduce Debrid solutions it has another access point of where my data needs to be associated.
> 
> Whats another oddity is that from my android device into the stremio web I can stream mediafusion live events but I'm unable to for the same stream on my PC using the same browser, Microsoft Edge. This leads me to believe that it maybe something on my desktop client side.
> 
> For added technical reference, stremio is hosted on 2 services via my LAN, stremio.local (ip:8083) and stremio-service.local (ip:11470), these both are opened via the main container and the VPN container in network mode.
> 
> Thought I'd add my 2 cents because I've had mixed results streaming with torrentio -> stremio web, which isn't present in the same stremio web with torrentio -> real debrid -> stremio web.
> 
> **EDIT** fixed wording on domain name.

Short answer is, it is a web browser limitation.
